### ISSUE TITLE
Release action is no longer maintained

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/reviewdog#1043]
I just noticed that the [create-release action](https://github.com/actions/create-release) is no longer being maintained by the Github team. I did not run into errors yet on the Reviewdog actions I support, other than the action not automatically being released to the marketplace (see https://github.com/actions/create-release/issues/99). However, maybe let's switch to a new maintained branch to be sure.

The Github team gives the following alternatives:

**Maintained Actions:**
* [elgohr/Github-Release-Action](https://github.com/elgohr/Github-Release-Action)
* [marvinpinto/action-automatic-releases](https://github.com/marvinpinto/action-automatic-releases)
* [softprops/action-gh-release](https://github.com/softprops/action-gh-release)
* [ncipollo/release-action](https://github.com/ncipollo/release-action)

@review-dog does anybody have a preference between these actions or is aware of a better action?

**Comment by Trim21** [comment]
maybe just use github cli `gh` https://github.com/cli/cli

**Comment by rickstaa** [comment]
@Trim21 ah, I was not aware of that. Looks like a good solution. Thanks for the update!

**Comment by rickstaa** [comment]
I updated the actions that are maintained by me. See https://github.com/reviewdog/action-black/blob/0d6daa02d36c2b9669bd71dd460d1e87df8ca097/.github/workflows/release.yml#L41-L46 for an example. The following actions still need to be updated:
- [x] https://github.com/reviewdog/action-black
- [ ] https://github.com/reviewdog/action-remark-lint
- [ ] https://github.com/reviewdog/action-pytest
- [ ] https://github.com/reviewdog/action-ansiblelint
- [ ] https://github.com/reviewdog/action-golangci-lint
- [ ] https://github.com/reviewdog/action-cpplint
- [ ] https://github.com/reviewdog/action-detect-secrets
- [ ] https://github.com/reviewdog/action-misspell
- [ ] https://github.com/reviewdog/action-brakeman
- [ ] https://github.com/reviewdog/action-suggester
- [ ] https://github.com/reviewdog/action-tflint
- [ ] https://github.com/reviewdog/action-hadolint
- [ ] https://github.com/reviewdog/action-rubocop
- [ ] https://github.com/reviewdog/action-shellcheck
- [ ] https://github.com/reviewdog/action-shellcheck
- [ ] https://github.com/reviewdog/action-setup
- [ ] https://github.com/reviewdog/action-depup
- [ ] https://github.com/reviewdog/action-staticcheck
- [ ] https://github.com/reviewdog/action-eslint
- [ ] https://github.com/reviewdog/action-tfsec
- [ ] https://github.com/reviewdog/action-actionlint
- [ ] https://github.com/reviewdog/action-markdownlint
- [ ] https://github.com/reviewdog/action-reek
- [ ] https://github.com/reviewdog/action-pyflakes
- [ ] https://github.com/reviewdog/action-vint
- [ ] https://github.com/reviewdog/action-languagetool
- [ ] https://github.com/reviewdog/action-shfmt
- [ ] https://github.com/reviewdog/action-composite-template
- [ ] https://github.com/reviewdog/action-nimlint
- [ ] https://github.com/reviewdog/action-eclint
- [ ] https://github.com/reviewdog/action-coffeelint
- [ ] https://github.com/reviewdog/action-stylelint
- [ ] https://github.com/reviewdog/action-template

**Comment by shogo82148** [comment]
done! https://github.com/reviewdog/reviewdog/issues/1043#issuecomment-1034823340
