### ISSUE TITLE
Support for running on Github Actions workflow_dispatch and other events

### ISSUE THREAD

**Issue by NickLarsenNZ** [reviewdog/reviewdog#1062]
As per https://github.com/reviewdog/action-rubocop/issues/37#issuecomment-941636085, the action cannot run properly unless it is on a pull request. That is because the code specifically looks for information from the PullRequest object:

https://github.com/reviewdog/reviewdog/blob/8c93ceaf90b675262a5386828501ba2b5a461df0/cienv/github_actions.go#L86

Could this be extended to support other github actions events such as `workflow_dispatch`? Github supplies the SHA in `github.sha`.

**Comment by NickLarsenNZ** [comment]
Actually it looks like it should fallback to this if the SHA is empty:

https://github.com/reviewdog/reviewdog/blob/8c93ceaf90b675262a5386828501ba2b5a461df0/cienv/github_actions.go#L96

From the [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), it appears `github.head_commit` is only available for `pull_request` or `pull_request_target` events. So maybe an additional fallback should be added, and as  mentioned in the issue description, use `github.sha`.

**Comment by AlexTMjugador** [comment]
v0.14.2 includes a change that should fix this issue. If that's not the case, please feel free to let us know so we can reopen it.
