### ISSUE TITLE
Install failing: 503 Egress is over the account limit.

### ISSUE THREAD

**Issue by marcinkunert** [reviewdog/reviewdog#1086]
I'm using reviewdog through https://github.com/nikitasavinov/checkstyle-action

It recently stopped working with a message:

`wget: server returned error: HTTP/1.1 503 Egress is over the account limit.`

It fails when creating [docker image](https://github.com/nikitasavinov/checkstyle-action/blob/master/Dockerfile) on this step:

`RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}`

with `ENV REVIEWDOG_VERSION` set to `v0.10.0`

**Comment by marcinkunert** [comment]
I've just noticed it did not work at 13:51 CET and 13:59 CET, but worked again fine 14:23 CET

**Comment by shogo82148** [comment]
I don't know why, but it looks an issue of GitHub.
https://github.com/github/feedback/discussions/8535

**Comment by marcinkunert** [comment]
@shogo82148 thanks for letting me know!
