### ISSUE TITLE
github-pr-check output should print github enterprise URL, if applicable

### ISSUE THREAD

**Issue by SirensOfTitan** [reviewdog/reviewdog#1398]
See:
https://github.com/reviewdog/reviewdog/blob/9f7fd10cac4a67490f93ba2b572c80bed695b9dc/service/github/githubutils/utils.go#L32

... I don't know how involved it would be to adjust the host here based on whether reviewdog is working within a github-enterprise context or github cloud context, but would be nice to get correct links here.

I'm very happy to submit a PR with a little assistance on how to approach if would be appreciated [I know it's often more trouble than it's worth!]

**Comment by dskleviathan** [comment]
I faced the same issue. In my opinion, we ought to use an environment variable to change the domain.

**Comment by shogo82148** [comment]
fixed by https://github.com/reviewdog/reviewdog/pull/1433
