### ISSUE TITLE
I want to konw which LLM do you uesd

### ISSUE THREAD

**Issue by lush-99** [reviewdog/reviewdog#1642]
This project is very useful, but I have some privacy requirements and would like to know if there is any interaction with a large model, and if there is a large model, which one is it?

Looking forward to hearing from you

**Comment by shogo82148** [comment]
Reviewdog itself does not interact with any large models.

**Comment by lush-99** [comment]
Can I understand that this model does not involve privacy issues

**Comment by shogo82148** [comment]
I do not understand what "this model" refers to.
reviewdog is not an AI project. it does not interact any LLM(Large language Models).
see the design doc for more detail: https://docs.google.com/document/d/1mGOX19SSqRowWGbXieBfGPtLnM0BdTkIc9JelTiu6wA/edit?usp=sharing

**Comment by lush-99** [comment]
ok, i will read it, thanks
