### ISSUE TITLE
-reporter=github-pr-review doesn't work on private repo

### ISSUE THREAD

**Issue by derekperkins** [reviewdog/reviewdog#171]
We have reviewdog working with github-pr-review on our public repos, but it isn't working on our private repo. It is running in CircleCI and it shows that it is exiting with a golint suggestion, but then the review never posts to the PR. The personal token has all repo permissions and is only in use by reviewdog, which shows recent usage, so the token is being used at some point. Do you have any suggestions on how to debug this further?

PS. I'd prefer to run github-pr-check, but that is overly backed up on your personal server at this point. Is this something easily self-hosted and registered ourselves through GitHub apps?

cc @josephbergevin

**Comment by haya14busa** [comment]
Sorry for the late replay.

Hmmm.. I cannot reproduce it.

- Can you see any errors or output from reviewdog command?
- Can you re-confirm the token has right permission? Can you get private repo data from GitHub API from the token?
- Can you put a command you used to run reviewdog and linters?
- CircleCI uses `bash -eo pipefail`. it might be related with the issue.

As for the github-pr-check, there is an issue. #145

> but that is overly backed up on your personal server at this point.

The server costs are almost zero right now and I'm started getting support by [opencollective](https://opencollective.com/reviewdog) to sustain the project.
If you just only cares about my money, it's more welcome to use github-pr-check.

**Comment by arindam2** [comment]
@haya14busa We are facing a similar issue:

```
export REVIEWDOG_GITHUB_API_TOKEN=e2f6a1f924e45098efbfa553eb1e952998ef0669
export GITHUB_API="https://example.githubenterprise.com/api/v3/"
export REVIEWDOG_INSECURE_SKIP_VERIFY=true
golint ./... | grep -v vendor | reviewdog -reporter=github-pr-review -f=golint -diff="git diff feature-branch"
reviewdog: cannot get repo owner from environment variable. Set CI_REPO_OWNER?
```

Unsetting GITHUB_API and REVIEWDOG_INSECURE_SKIP_VERIFY makes no difference.

**Comment by josephbergevin** [comment]
@haya14busa looks like our key had just gone bad in the end. `github-pr-review` seems to be working great now.
