### ISSUE TITLE
installation failed in gitlab-ci

### ISSUE THREAD

**Issue by cold-bin** [reviewdog/reviewdog#1757]
wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s [vX.Y.Z]

reviewdog/reviewdog info checking GitHub for tag '[vX.Y.Z]'
reviewdog/reviewdog crit unable to find '[vX.Y.Z]' - use 'latest' or see https://github.com/reviewdog/reviewdog/releases for details
Cleaning up file based variables

**Comment by shogo82148** [comment]
try `wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s v0.17.4`

**Comment by cold-bin** [comment]
$ export REVIEWDOG_INSECURE_SKIP_VERIFY=true
$ export GOPROXY="https://goproxy.cn,direct/"
$ export REVIEWDOG_GITLAB_API_TOKEN="[MASKED]"
$ reviewdog -f=golangci-lint -reporter=gitlab-mr-discussion -log-level=debug
reviewdog: fail to get diff: failed to run git diff: exit status 128

in gitlab-ci

**Comment by cold-bin** [comment]
git fetch before reviewdog is ok
