### ISSUE TITLE
accept the GitHub Marketplace Developer Agreement

### ISSUE THREAD

**Issue by shogo82148** [reviewdog/reviewdog#1791]
I want to publish reviewdog GitHub Actions to the GitHub Marketplace, but I can't.
GitHub says "reviewdog must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it."

<img width="929" alt="image" src="https://github.com/reviewdog/reviewdog/assets/1157344/3cc0fe1e-b9c7-43a3-af37-d34d6dd8ee66">

@haya14busa Can you accept the GitHub Marketplace Developer Agreement?

**Comment by haya14busa** [comment]
Done. Can you try again?

**Comment by shogo82148** [comment]
It looks fine. Thanks!

<img width="944" alt="image" src="https://github.com/reviewdog/reviewdog/assets/1157344/e15ba0d1-22c8-4f37-8df8-1068ab303ae2">
