### ISSUE TITLE
Linting isn't files inside subdirectory

### ISSUE THREAD

**Issue by sokumon** [reviewdog/reviewdog#1821]
I am using reviewdog & black via this [Github Action](https://github.com/reviewdog/action-black) in my python library.
When the action is running, it (black) is ignoring the .py files in the subfolders even if the workdir input is set.
Though the output of BLACK_CHECK_FILE_PATHS shows list of all .py files even in subfolders.
My project's directory structure looks like this:
.
├── setup.py
├── library-dir/
│   ├── __ init __.py
│   ├── mod_one.py
│   ├── mod_two.py
│   └── mod_three.py
├── docs  
├── tests
├── README.md
└── LICENSE.txt
The problem is that only setup.py is being lint and all files under the library-dir have been ignored.
To debug this problem, I did set the verbose flag to true only to see it Blacks outputs saying it will reformat all the paths.

I am not sure if this issue should be here at the black project.

Kindly guide me what am I doing wrong.

**Comment by massongit** [comment]
I don't understand your action-black options and your black settings.
Therefore, it would be helpful if you could provide an example of your workflow run.
