### ISSUE TITLE
Are v0.19.0 and v0.20.0 the same version?

### ISSUE THREAD

**Issue by sksat** [reviewdog/reviewdog#1829]
It appears that both [v0.19.0](https://github.com/reviewdog/reviewdog/releases/tag/v0.19.0) and [v0.20.0](https://github.com/reviewdog/reviewdog/releases/tag/v0.20.0) reference the same commit hash.
There is no mention of this in the release notes, and there seems to be no changelog available for v0.20.0.

**Comment by massongit** [comment]
v0.19.0 and v0.20.0 are same.
The reason why this happened is because I ran the release CI https://github.com/reviewdog/reviewdog/actions/runs/9822921105/job/27121022131 twice.
I'm sorry...

**Comment by haya14busa** [comment]
No problem!

@massongit can you update the changelog and mention v20 is the same as v19?

**Comment by massongit** [comment]
I update it: https://github.com/reviewdog/reviewdog/releases/tag/v0.20.0

**Comment by haya14busa** [comment]
Can you update https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md?

**Comment by sksat** [comment]
thanks!
