### ISSUE TITLE
Parsers should be able to return results for multiple tools

### ISSUE THREAD

**Issue by sagikazarmark** [reviewdog/reviewdog#186]
[Golang CI](http://golangci.com/) is a great tool, collecting a number of Go linting tools in one binary. It is capable of outputting a checkstyle format (and a custom json format as well) which can contain the actual linter which raised an issue.

It would be nice, if the actual tool could be detected by the parser itself.

**Comment by haya14busa** [comment]
golangci-lint reports linter name in the message, so it should be fine for most cases.
