### ISSUE TITLE
Running a private reviewdog server

### ISSUE THREAD

**Issue by jbotelho2-bb** [reviewdog/reviewdog#195]
I'd like to be able to run a private reviewdog server, so that we can use the github-pr-check reporter against GitHub Enterprise. Do you have the source code and/or any documentation on the server?

**Comment by mediavrog** [comment]
Same here. It would be grat if you could open source the server part, so you can reduce load on your private server and we can integrate it into our infrastructure.

**Comment by haya14busa** [comment]
Now reviewdog can report via Check API if it's running on GitHub Actions. https://medium.com/@haya14busa/automated-code-review-on-github-actions-with-reviewdog-for-any-languages-tools-20285e04448e

I don't have a plan to support running a private reviewdog server considering GitHub Actions can solve this problem.

**Comment by haya14busa** [comment]
related #145

**Comment by jbotelho2-bb** [comment]
@haya14busa that doesn't solve the issue, as we don't have GitHub actions available on GitHub Enterprise.

**Comment by haya14busa** [comment]
Actually I already opened every code in this repository including the reviewdog server, but I don't recommend users to use it. Please feel free to use it at your own decision.

Also, GitHub Actions itself is beta for public GitHub too and they seem to extend it more and more. including enterprise usecases.

**Comment by jbotelho2-bb** [comment]
When I say GitHub Enterprise, I mean their [on-premise GitHub server offering](https://github.com/enterprise). According to [a recent blog post](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/), Actions won't be available there until next year.

I can poke around with the server in the meantime; I didn't realize it was already in the repo. I'm assuming this is it? https://github.com/reviewdog/reviewdog/blob/master/doghouse/appengine/main.go
