### ISSUE TITLE
go get failed unless GO111MODULE=on

### ISSUE THREAD

**Issue by hamakn** [reviewdog/reviewdog#219]
This is expected behavior?
```
% go version
go version go1.12.4 darwin/amd64

% go get -u github.com/reviewdog/reviewdog/cmd/reviewdog
package github.com/google/go-github/v24/github: cannot find package "github.com/google/go-github/v24/github" in any of:
        /usr/local/Cellar/go/1.12.4/libexec/src/github.com/google/go-github/v24/github (from $GOROOT)
        /Users/hamakn/dev/src/github.com/google/go-github/v24/github (from $GOPATH)

% GO111MODULE=on go get -u github.com/reviewdog/reviewdog/cmd/reviewdog
// OK if there is no Gopkg.lock
```

**Comment by haya14busa** [comment]
Probably because go-github v25 was released, but i'm not sure.
https://github.com/google/go-github/releases/tag/v25.0.0

It might be the bug of go-get and it's not the problem of reviewdog.

Please use  `GO111MODULE=on`, install reviewdog binary (https://github.com/reviewdog/reviewdog#installation), or report the bug to go project.

**Comment by haya14busa** [comment]
I updated dependencies and confirmed `go get` worked.
Still not sure whether or not it's bug of go.

**Comment by aimof** [comment]
It seems to be caused by -u option.

[Usage of go get -u](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies)

> A common mistake is thinking go get -u foo solely gets the latest version of foo. In actuality, the -u in go get -u foo or go get -u foo@latest means to also get the latest versions for all of the direct and indirect dependencies of foo. A common starting point when upgrading foo is instead to do go get foo or go get foo@latest without a -u (and after things are working, consider go get -u=patch foo, go get -u=patch, go get -u foo, or go get -u).

-u option cannot solve the dependencies but get latest of all repositories it depends on.

Thank you.

**Comment by haya14busa** [comment]
No. It's reproducible without `-u`.

e.g.
```
GO111MODULE=auto go get github.com/haya14busa/go-get-non-latest-dep-test
```

**Comment by haya14busa** [comment]
ref: https://github.com/golang/go/blob/a16dcc00526dbb5ff411004c987a4182a8d68e7c/src/cmd/go/internal/load/pkg.go#L1011-L1019
https://golang.org/issue/25069

**Comment by aimof** [comment]
It's my mistake about -u.
I saw your go-get-non-latest-dep-test repo and run.

distro: Ubuntu 18.04
go: 1.12.4

then

```
$ GO111MODULE=auto go get github.com/haya14busa/go-get-non-latest-dep-test
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
```

* If GO111MODULE=auto and workdir is under $GOPATH/src, GO111MODULE is off. [resource](https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support) So, go-github is got without version info.
* However, go-get-non-latest-dep-test repo imports github.com/google/go-github/v24 but v24 depends on go mod.
* So we must GO111MODULE=on when go get.

**Comment by aimof** [comment]
Sry, I wrong.
I can import latest(v25) when GO111MODULE=off

https://github.com/aimof/go-get-non-latest-dep-test/commit/c07a1c5df088c72e8bab861a882132ff4151eaa2

**Comment by hamakn** [comment]
Last Thursday I used `wget` command in README instead of `go get` to repair our problem.

@haya14busa 
Thank you for your research and quick temporary fix, even though it was not caused by reviewdog.
