### ISSUE TITLE
this is not MergeRequest build.

### ISSUE THREAD

**Issue by guzuqing** [reviewdog/reviewdog#221]
in gitlabci find a error

$ export GITLAB_API="https://gitlab.hutaojie.com/api/v4"
$ pwd
/Users/dual/builds/bb28ea26/0/group_runners_test/test_project
$ reviewdog -reporter=gitlab-mr-commit
this is not MergeRequest build.
Job succeeded

how to fix it

**Comment by korjavin** [comment]
You can fix it by starting this stage on MR

**Comment by haya14busa** [comment]
Please reopen it with more detail information if the problem is not fixed.

**Comment by iamazy** [comment]
> Please reopen it with more detail information if the problem is not fixed.

@haya14busa Hi, I still have this problem, I don't know if it's because I didn't merge `.gitlab-ci.yml` and `.reviewdog.yml` into the repo in advance
