### ISSUE TITLE
--reporter=github-pr-review does not work with sub directory

### ISSUE THREAD

**Issue by nasa9084** [reviewdog/reviewdog#225]
when run go vet and reviewdog in sub directory, reviewdog do nothing.
from my forking & analysis, `-strip` option is working but wd in `FilterCheck()` is not working well.

## info

* go version: 1.12 (`govet` format also not work, I use `-efm "%f:%l:%c: %m`)
* install with install.sh as README
* on CircleCI Enterprise 2.x
* with GitHub Enterprise

## how I did

configured reviewdog run with go vet in `.circleci/config.yml` like:

```
- run:
  command: |
    test ${CI_PULL_REQUEST} || exit 0
    cd subdir
    curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
    go vet ./... 2>&1 | ./bin/reviewdog -name "go vet" -efm "%f:%l:%c: %m" -reporter=github-pr-review || true
```
before the commands,  I configured api token and url as environment variable.

when directory structure is like:

```
|- .circleci/config.yml
|- directories including codes with not go codes
|- subdir
    |- go codes...
```

`go vet` reports `unreachable code` which i created for testing reviewdog, and the line is in PR changes like:
<img width="992" alt="スクリーンショット 2019-06-18 17 14 17" src="https://user-images.githubusercontent.com/11725486/59664723-8a4b2280-91ec-11e9-8d48-f2af6e5cb9c2.png">

## repro example

https://github.com/nasa9084/reviewdog-test/pull/1

I want review comment by reviewdog but not

```
#!/bin/bash -eo pipefail
test ${CI_PULL_REQUEST} || exit 0
cd subdir
curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
go vet ./... 2>&1 | ./bin/reviewdog -name "go vet" -efm "%f:%l:%c: %m" -reporter=github-pr-review || true

reviewdog/reviewdog info checking GitHub for latest tag
reviewdog/reviewdog info found version: 0.9.12 for v0.9.12/Linux/x86_64
reviewdog/reviewdog info installed ./bin/reviewdog
```

**Comment by mattn** [comment]
Could you please explain more information to reproduce? directory structure and repro steps.

**Comment by nasa9084** [comment]
sorry I will add more informations

**Comment by nasa9084** [comment]
I have added some information and created example (with github.com)

**Comment by qwerty2501** [comment]
Hello.
I faced a similar problem too.
It seems to occur when reviewdog  directory executed is different  from the Arranged ".git" directory.
There is workaround that specifying strip argument  for this problem.  But strip argument is worked local reporter only.
Is there any reason why the strip argument only works for local reporter?
