### ISSUE TITLE
No output when running reviewdog w/ stylelint

### ISSUE THREAD

**Issue by jpjamipark** [reviewdog/reviewdog#226]
When running the command:

 `stylelint theme.scss | reviewdog -f="stylelint" -diff="git diff master"`

there's no output. Not sure why this happens, works fine when running reviewdog with golint. Both `git diff master` and `stylelint theme.scss` have valid outputs.

Theme.scss:
```
body
{
  background-color: black;




}

```

**Comment by nckcol** [comment]
I think this issue was closed by a mistake. PR which referenced it was fixing another issue - #266

Instead, this PR https://github.com/reviewdog/errorformat/pull/108 should fix it
