### ISSUE TITLE
Discussion in gitlab instance looks really strange.

### ISSUE THREAD

**Issue by korjavin** [reviewdog/reviewdog#249]
![image](https://user-images.githubusercontent.com/148765/62422986-f3ff8d00-b6c3-11e9-86f2-667b2b51fa3e.png)
Why I see this "download" buttons?

**Comment by haya14busa** [comment]
I don't know why. Maybe due to update(bug) of GitLab?

**Comment by korjavin** [comment]
They could have changed something. What kind of help do you want from me?

**Comment by haya14busa** [comment]
Can you report this issue to GitLab is you are fine? That would be really helpful.

**Comment by haya14busa** [comment]
Just a memo: I can reproduce this issue.
https://gitlab.com/reviewdog/reviewdog/merge_requests/196

**Comment by korjavin** [comment]
O

> Just a memo: I can reproduce this issue.
> https://gitlab.com/reviewdog/reviewdog/merge_requests/196

This link looks like a broken one

**Comment by haya14busa** [comment]
Just to confirm, you mean the link itself is not broken and we can see a download link, right?
![image](https://user-images.githubusercontent.com/3797062/64912646-390bea00-d76d-11e9-99e4-4d48bece57f2.png)

**Comment by korjavin** [comment]
This link "download" is working. (but not what I want though)

By broken link I meant that https://gitlab.com/reviewdog/reviewdog/merge_requests/196, that you shared is broken for me.

**Comment by haya14busa** [comment]
Oh, I didn't notice that I somehow created the repository as private in GitLabe... I changed it to public. Thanks!

Anyway, I don't have time to investigate this issue by myself.

**Comment by AlphaWong** [comment]
@haya14busa 
I think is the path of the file have problem
```
https://github.com/reviewdog/reviewdog/blob/15d564ee6c6d44ebf80b78a812d3b56fdd030758/service/gitlab/gitlab_mr_discussion.go#L114
```

As when I inspect the 
```
https://gitlab.com/reviewdog/reviewdog/raw/347199097e38e8c83ff90e7422de3c779c6bea25/resultmap.go`

https://gitlab.com/reviewdog/reviewdog/blob/347199097e38e8c83ff90e7422de3c779c6bea25/resultmap.go
```

Can u replace `raw` to `blob` to see Gitlab can locate the file and file line?

**Comment by haya14busa** [comment]
That's not path reviewdog specified but GitLab service uses it.

As I said, I suspect it's a bug of GitLab. Can anyone report it to GitLab?

**Comment by fechnert** [comment]
I can reproduce this with reviewdog 0.9.16 and GitLab 12.5.3

**Comment by haya14busa** [comment]
https://gitlab.com/gitlab-org/gitlab/issues/196872

**Comment by haya14busa** [comment]
I fixed it and released a new version.
