### ISSUE TITLE
[doghouse] migrate to appengine go112

### ISSUE THREAD

**Issue by arnottcr** [reviewdog/reviewdog#266]
The appengine `go1` runtime (latest version `go1.9`), is now [officially deprecated](https://cloud.google.com/appengine/docs/deprecations) and new deployments are no longer possible. Do you have a plan for migrating to `go112`?

**Comment by haya14busa** [comment]
The appengine server is using go111 and it won't be deprecated.
https://github.com/reviewdog/reviewdog/blob/e9c80d8135dabcbd8afafb482cd74a8f5436ac62/doghouse/appengine/app.yaml#L4

**Comment by arnottcr** [comment]
Hmm, sorry for having missed that; I guess all the [lingering usage of `google.golang.org/appengine`](https://github.com/reviewdog/reviewdog/search?l=Go&q=google.golang.org%2Fappengine) confused me.

I really thought that these packages did not play nice with go111 runtime, but [that is incorrect](https://cloud.google.com/appengine/docs/standard/go111/go-differences#importing-appengine-sdk). Considering [their urging](https://cloud.google.com/appengine/docs/standard/go111/go-differences#migrating-appengine-sdk) and [sunset in go112](https://cloud.google.com/appengine/docs/standard/go112/go-differences#migrating-appengine-sdk) is it worth refactoring them out of doghouse? I am more than happy to contribute the change.

**Comment by haya14busa** [comment]
Thanks for the information! Yes, we should anyway refactor them out and migrate to go 11.2.
(and actually I found that the cloud console said "A version of your app is using a deprecated version of Go. Please upgrade before October 1, 2019."...)
If you can contribute to the migration, I really appreciate it!

**Comment by haya14busa** [comment]
hmm... I encountered 2 type of errors after the deploy. I temporarily roll-backed the doghouse server to go111 and i'm investigating the reason. 

1. 
```
reviewdog: post failed for staticcheck: status=400: failed to get branch/diff: fail to parse diff: GET https://api.github.com/repos/reviewdog/reviewdog/pulls/313: 401 Bad credentials []
```

2.  /gh_/webhook request
```
2019/09/21 09:25:44 http: panic serving 127.0.0.1:51412: runtime error: invalid memory address or nil pointer dereference goroutine 102 [running]: net/http.(*conn).serve.func1(0xc00049b7c0) /usr/local/go/src/net/http/server.go:1769 +0x139 panic(0xa8bce0, 0x117c0b0) /usr/local/go/src/runtime/panic.go:522 +0x1b5 cloud.google.com/go/datastore.newTransactionSettings(0xc000377a00, 0x1, 0x1, 0xc0002c8270) /go/pkg/mod/cloud.google.com/go/datastore@v1.0.0/transaction.go:44 +0x77 cloud.google.com/go/datastore.(*Client).RunInTransaction(0xc0002c8240, 0xc72c20, 0xc00007bf80, 0xc000377a10, 0xc000377a00, 0x1, 0x1, 0x0, 0x0, 0x0) /go/pkg/mod/cloud.google.com/go/datastore@v1.0.0/transaction.go:162 +0xfe github.com/reviewdog/reviewdog/doghouse/server/storage.(*GitHubInstallationDatastore).Put(0x11ade28, 0xc72c20, 0xc00007bf80, 0xc0004c5760, 0xc00040b720, 0x0) /tmp/staging/srv/doghouse/server/storage/installation.go:44 +0x11d main.(*githubWebhookHandler).handleCheckSuiteEvent(0xc0002d2210, 0xc72c20, 0xc00007bf80, 0xc000360000, 0x269c, 0x3e00, 0xb8a11d, 0xe, 0xc000522b10) /tmp/staging/srv/doghouse/appengine/github_webhook.go:63 +0x138 main.(*githubWebhookHandler).handleWebhook(0xc0002d2210, 0xc71b20, 0xc0004b9180, 0xc000127b00) /tmp/staging/srv/doghouse/appengine/github_webhook.go:37 +0x1d7 net/http.HandlerFunc.ServeHTTP(0xc0001e1d10, 0xc71b20, 0xc0004b9180, 0xc000127b00) /usr/local/go/src/net/http/server.go:1995 +0x44 net/http.(*ServeMux).ServeHTTP(0xc00029eec0, 0xc71b20, 0xc0004b9180, 0xc000127b00) /usr/local/go/src/net/http/server.go:2375 +0x1d6 net/http.(*ServeMux).ServeHTTP(0x11910c0, 0xc71b20, 0xc0004b9180, 0xc000127b00) /usr/local/go/src/net/http/server.go:2375 +0x1d6 net/http.serverHandler.ServeHTTP(0xc0002ce340, 0xc71b20, 0xc0004b9180, 0xc000127b00) /usr/local/go/src/net/http/server.go:2774 +0xa8 net/http.(*conn).serve(0xc00049b7c0, 0xc72c20, 0xc00029fb40) /usr/local/go/src/net/http/server.go:1878 +0x851 created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by haya14busa** [comment]
Fixed!
