### ISSUE TITLE
Add support for gogs

### ISSUE THREAD

**Issue by thesyncim** [reviewdog/reviewdog#29]

**Comment by haya14busa** [comment]
can you give me a API docs equivalent to GitHub's PullRequest API?

**Comment by thesyncim** [comment]
sryfor the noise  but gogs API is [incomplete](https://github.com/gogits/go-gogs-client/wiki)

**Comment by thesyncim** [comment]
sry for the noise  but gogs API is incomplete

**Comment by lafriks** [comment]
Gitea has more complete api, including status api. What methods are needed?

**Comment by donny-dont** [comment]
@haya14busa Drone has https://github.com/drone/go-scm which handles github gitlab and gogs/gitea.

**Comment by haya14busa** [comment]
Thanks. Looks like the real API has not been implemented yet, but looks interesting.

**Comment by haya14busa** [comment]
Pull Requests are welcome, but I don't have plan to implement it.
