### ISSUE TITLE
Output from piping tflint to reviewdog is empty

### ISSUE THREAD

**Issue by jason-riddle** [reviewdog/reviewdog#306]
I'm having trouble figuring out the correct syntax for [tflint](https://github.com/wata727/tflint). Here's an example of tflint messages.

```
tflint --format json | jq -r '.errors[].message'

main.tf:290,1-1: Argument or block definition required; An argument or block definition is required here.
main.tf:14,1-7: Reserved block type name in provider block; The block type name "locals" is reserved for use by Terraform in a future version.
```

I've tried piping it via the following

```
tflint --format json | jq '.errors[].message' | reviewdog -efm="%f:%l:%c-%*[0-9]: %m" -diff="git diff master"
```

but no output is shown. Output should be shown from reviewdog when used locally correct? If so, what am I missing?

**Comment by haya14busa** [comment]
reviewdog only reports output which is in diff.
You can use errorformat CLI (https://github.com/reviewdog/errorformat#cli-tool) to check the errorformat is correct or not regardless of the diff.

**Comment by haya14busa** [comment]
Actually, the format seems to be wrong. The correct format is
```
%f:%l,%c-%*[0-9]: %m
```

Use `,` after `%l`

**Comment by jason-riddle** [comment]
> reviewdog only reports output which is in diff.
> You can use errorformat CLI (https://github.com/reviewdog/errorformat#cli-tool) to check the errorformat is correct or not regardless of the diff.

Ah I missed that. Thank you!
