### ISSUE TITLE
New GitHub Action: tflint

### ISSUE THREAD

**Issue by Vlaaaaaaad** [reviewdog/reviewdog#322]
Hi,

Based on the GitHub Actions example in the reviewdog organization [I created a new action for running tflint](https://github.com/Vlaaaaaaad/tflint-action).

Should I keep it in its own repo? Should I somehow add it to this org? I don't mind maintaining it in my own repo, but I don't know what the process is here.

Thank you for the awesome project!

**Comment by haya14busa** [comment]
Cool! :sparkles:
You are the first one who created reviewdog GitHub Actions other than me :)

If you're fine, I'd like to move the repo under reviewdog org and also invite you as a maintainer.
I invited you to reviewdog org if you're interested in it.

**Comment by haya14busa** [comment]
I'm also fine that you maintain the repository under your account.
In that case, let me add a link to your action from README :)

**Comment by Vlaaaaaaad** [comment]
For consistency and to showcase reviewdog as **the tool** to do checks feedback I'd rather put it in the `reviewdog` org.

I'll accept the invitation and copy/ move the repo over later today.

Thank you!

**Comment by Vlaaaaaaad** [comment]
PR to have this included in the `reviewdog` GitHub Organization created so I am closing this.

**Comment by Vlaaaaaaad** [comment]
Ahem, PR is at https://github.com/reviewdog/action-tflint/pull/1
