### ISSUE TITLE
New reporter=github-check: Support non Pull Request run and changes outside diff

### ISSUE THREAD

**Issue by haya14busa** [reviewdog/reviewdog#332]
https://developer.github.com/changes/2019-09-06-more-check-annotations-shown-in-files-changed-tab/

**Comment by haya14busa** [comment]
Maybe we can use event.compare
https://github.com/reviewdog/reviewdog/compare/7a17ca64b1fe...febdd4bf26c6
to get diff.

**Comment by haya14busa** [comment]
Raw diff URL https://github.com/reviewdog/reviewdog/compare/7a17ca64b1fe...febdd4bf26c6.diff

**Comment by haya14busa** [comment]
TODO(haya14busa): document

**Comment by ruudk** [comment]
Would it be possible to release this version as alpha on Github? I'm having difficulties building this binary.

**Comment by ruudk** [comment]
It seems that the "changes outside diff" only work for non-PR builds, is that correct? 

I just tested this out on a test PR but it filters out anything that is not in the `pullRequestDiff`. I really want to add annotations on files that were not changed too.

**Comment by haya14busa** [comment]
#364 fixed the issue.
