### ISSUE TITLE
[github-pr-check] Support mixed levels

### ISSUE THREAD

**Issue by ruudk** [reviewdog/reviewdog#343]
Maybe this is a limitation in Github PR Checks but I'm trying to run reviewdog 3 times in the same Action that all report in their own level, so `info`, `warning` and `error`:

```workflow.yaml
name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: install reviewdog
        run: |
          wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE
      - name: run reviewdog info
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        run: |
          echo "index.php:3 hi\nindex.php:53 halloo" | ./reviewdog -efm="%f:%l %m" -name="php" -reporter="github-pr-check" -level="info"
      - name: run reviewdog warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        run: |
          echo "index.php:70 OOPS"  | ./reviewdog -efm="%f:%l %m" -name="php" -reporter="github-pr-check" -level="warning"
      - name: run reviewdog error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        run: |
          echo "index.php:35 better to use X"  | ./reviewdog -efm="%f:%l %m" -name="php" -reporter="github-pr-check" -level="error"
```

Somehow only the latest error shows up. I have the feeling that either Reviewdog always overwrites the PR-check results, or that Github does not support multiple levels per PR-Check.

Any idea how to solve this?

**Comment by tboby** [comment]
Github supports multiple levels per PR-Check.
It appears that the `CheckResult` type doesn't store a level per check, which it would need to in order to support this. 
https://github.com/reviewdog/reviewdog/blob/f97a4e3dcf58384f7a55d15dbde633ffcbcf6ff0/reviewdog.go#L35

**Comment by haya14busa** [comment]
Can you try using different ` -name=` for each run? 
This is GitHub issue. GitHub Check automatically merge(?) check runs with the same name.

**Comment by tboby** [comment]
One shouldn't have to run the same analyser three times to get mixed levels though :)

We just decided not to use reviewdog for github and use the Checks API ourselves manually because of this limitation: https://github.com/cwtools/cwtools-action/blob/master/lib/cwtools.rb

**Comment by haya14busa** [comment]
@tbody You are describing a different issue. Please read the ruudk's comment.
 This issue is level per **check** but I guess you are talking about level per **annotation** (`CheckResult` in reviewdog name).

As for per annotation level, errorformat can parse error level, so it's possible to implement it, but not implemented yet.

**Comment by pietrodn** [comment]
I'm having a similar problem (comments overwriting each other) with GitHub PR review mode in #1911.
