### ISSUE TITLE
Option to disable filtering per runner

### ISSUE THREAD

**Issue by ruudk** [reviewdog/reviewdog#345]
I really like the work that has been done in https://github.com/reviewdog/reviewdog/issues/332 to implement `github-check`. Now that Github allows to add annotations to any file, and not just changed files, we can do all kinds of cool review checks. But the problem with the current implementation is that it doesn't work yet for PR's.

I'm working on a linter that checks if a given file has a corresponding unit test. Let's say you have a PR that changes a line somewhere in file `hello.go`. 

The linter should add an annotation to `hello.go` when the file `hello_test.go` is missing. 

Example:
```
echo 'hello.go:1 Could not find hello_test.go' | reviewdog -efm="%f:%l %m"
```

This works great, as long as the changed file in my PR is on line 1:
```
Findings (1)
Filtered Findings (0)
```

But if my change is somewhere else in the file, and not line 1, it will be filtered:
```
Findings (0)
Filtered Findings (1)
```

## Possible solution

Add option to disable this filtering on a per-runner basis in `.reviewdog.yaml`.

**Comment by haya14busa** [comment]
Sry for the late response. #364 fixed the issue and github-check now works for files outside diff regardless it's a pull-request or not.

Currently, I don't have a plan to implement an option to disable filtering per runner.
