### ISSUE TITLE
New GitHub Action: rubocop

### ISSUE THREAD

**Issue by mgrachev** [reviewdog/reviewdog#356]
Hi there!

I have created new GitHub Action to run rubocop with reviewdog - https://github.com/mgrachev/action-rubocop

May I create a repository in the organization @reviewdog and then move it there?

**Comment by haya14busa** [comment]
SG!

**Comment by mgrachev** [comment]
@haya14busa Done - https://github.com/reviewdog/reviewdog/pull/366

**Comment by haya14busa** [comment]
:100: :+1:
