### ISSUE TITLE
Github Action: hadolint

### ISSUE THREAD

**Issue by hazcod** [reviewdog/reviewdog#357]
hadolint is a linter for Dockerfiles.

**Comment by mgrachev** [comment]
@hazcod https://github.com/mgrachev/action-hadolint

@haya14busa What do you think about moving this action to reviewdog organization?

**Comment by haya14busa** [comment]
Looks good! :+1:

**Comment by mgrachev** [comment]
Done - https://github.com/reviewdog/action-hadolint
