### ISSUE TITLE
EClint format question

### ISSUE THREAD

**Issue by zbeekman** [reviewdog/reviewdog#397]
I'm having trouble understanding how to construct the proper format string.

I've gotten something to work using [the online error fomrat sandbox](https://reviewdog.github.io/errorformat-playground/?efms=%25-P%25f%0A%25E%25*%5B%5C+%5D%25l%3A%25c%25*%5B%5C+%5D%25*%5B%E2%9D%8C%5D%25*%5B%5C+%5D%25m%0A%25Z%25*%5B%5C+%5D%25m%0A%25-Q&text=src%2Ftests%2Floadtxt%2Ftest_loadtxt.f90%0A++++35%3A01+%E2%9D%8C+invalid+indent+size%3A+1%2C+expected%3A+0%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++36%3A01+%E2%9D%8C+invalid+indent+size%3A+2%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++37%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++39%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++40%3A01+%E2%9D%8C+invalid+indent+size%3A+2%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++41%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++43%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++44%3A01+%E2%9D%8C+invalid+indent+size%3A+2%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++45%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++47%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++48%3A01+%E2%9D%8C+invalid+indent+size%3A+2%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++49%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++50%3A01+%E2%9D%8C+invalid+indent+size%3A+3%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++51%3A01+%E2%9D%8C+invalid+indent+size%3A+1%2C+expected%3A+0%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0Asrc%2Ftests%2Ftest_dummy.f90%0A++++02%3A01+%E2%9D%8C+invalid+indent+size%3A+2%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29%0A++++03%3A01+%E2%9D%8C+invalid+indent+size%3A+2%2C+expected%3A+4%0A+++++++++++++++++++++++++++++++++++++++++++++++++%28EditorConfig+indent_size+https%3A%2F%2Fgoo.gl%2FQtGB8R%29)

But I can't figure out how to setup reviewdog to reproduce this. Specifically, do I need to use the reviewdog.yml file? Could I pass the fmt on the command line? If so, how?

**Comment by haya14busa** [comment]
You can pass multiple `-efm` flags if you want to pass the formats via cli flags. 
e.g.
```
-efm="%-P%f" -efm="%E%*[\ ]%l:%c%*[\ ]%*[❌]%*[\ ]%m" ...
```
