### ISSUE TITLE
New Linter: eclint

### ISSUE THREAD

**Issue by aslafy-z** [reviewdog/reviewdog#404]
Hello!

I added support for eclint. You can find it in here: https://github.com/aslafy-z/reviewdog-eclint-action.

**Comment by haya14busa** [comment]
Can you move the repo under reviewdog org and/or release the action to the marketplace?
Also, can you clean it up a bit more? e.g. Screenshot still uses eslint and eclint link is broken.

**Comment by aslafy-z** [comment]
I just moved it to https://github.com/reviewdog/action-eclint. I have some trouble to trigger the demo, it does not matches my errors..

**Comment by haya14busa** [comment]
Please check eclint results are correctly passed to reviewdog as stdin.

It looks very suspicious to me.
https://github.com/reviewdog/action-eclint/blob/bb520cccb123796d890eb131fc43eab3e2afd390/entrypoint.sh#L16
