### ISSUE TITLE
422 Unprocessable Entity with reporter=github-pr-review

### ISSUE THREAD

**Issue by Graham42** [reviewdog/reviewdog#429]
I'm getting an error message when trying to use `-reporter=github-pr-review`
```
reviewdog: POST https://.../pulls/9/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:}]
```
Would love to have more verbose logging to find out what request is being made to see where the issue is. Right now there's no way to know if it's reviewdog or some strangeness with the GitHub Enterprise instance.

**Comment by Graham42** [comment]
May be related to https://github.com/google/go-github/issues/1136

**Comment by haya14busa** [comment]
related: #354 

New go-github version (v29) should fix the issue.

**Comment by haya14busa** [comment]
Released new version. https://github.com/reviewdog/reviewdog/releases/tag/v0.9.16

**Comment by Graham42** [comment]
Thank you for the quick response! This no reveals the underlying error, opened new issue: https://github.com/reviewdog/reviewdog/issues/434
