### ISSUE TITLE
Error creating review with -reporter=github-pr-review

### ISSUE THREAD

**Issue by Graham42** [reviewdog/reviewdog#434]
reviewdog version: v0.9.16

I'm getting an error message when trying to use `-reporter=github-pr-review` that `The commitOID is not part of the pull request`
```
reviewdog: POST https://.../pulls/9/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:The commitOID is not part of the pull request}]
```

**Comment by haya14busa** [comment]
How did you run reviewdog and how did you get commit id? As described in the error message, commit id is wrong.

**Comment by Graham42** [comment]
:man_facepalming: sorry! This is because of Jenkins behaviour. It's configured to build the merge result of the branch and `master` on PR builds, so the local `HEAD` commit doesn't actually exist in the PR, as you say.

I was doing
```sh
git rev-parse HEAD
```

For others who may find this, my solution was to use:
```
git rev-parse origin/${BRANCH_NAME}
```
