### ISSUE TITLE
Return error exit code when one of the checks fails

### ISSUE THREAD

**Issue by ruudk** [reviewdog/reviewdog#446]
I'm running Reviewdog in Github Actions. Reviewdog checks `php-cs-fixer` and `phpstan`. When it finds errors, they are reported as separate checker results:
<img width="200" alt="Screenshot 2020-01-16 at 11 57 18" src="https://user-images.githubusercontent.com/104180/72519300-5ce45700-3857-11ea-908c-e8881f175a8c.png">

But, as you can see, the `reviewdog` step is ✅.

This makes it hard to work with, because for the `deploy` step (not in screenshot) I want to depend on the success of `reviewdog + phpunit` step. But the `reviewdog` step is always green. Even tho it found errors.

Would be great if reviewdog has an option to return an error exit code when one of the runners find an error.

**Comment by Edulopez** [comment]
Does your reviewdog is integrated phpstan or any other lint you use?

> "reviewdog" provides a way to post review comments to code hosting service, such as GitHub, automatically by integrating with any linter tools with ease.

**Comment by ruudk** [comment]
@Edulopez I don't understand what you mean.

**Comment by Edulopez** [comment]
I think the way reviewdog works is that it has a set of linters that it will run a use their result. If you haven't integrated your lints in reviewdog It will be working as a separate tool.

@haya14busa would you check this issue?

**Comment by haya14busa** [comment]
@Edulopez I don't understand what you're trying to say, but I'm guessing the answer is that
@ruudk uses phpstan and php-cs-fixer with reviewdog integration.

It makes sense that users want to expect that reviewdog fails on exit when it finds issues in some use cases as @ruudk described.

**Comment by DmitryLanda** [comment]
Nice feature request, I wish to have same feature also.
Example:
 `$HOME/bin/phpcs.phar --extensions=php --report=checkstyle --parallel=10 someFile.php | reviewdog -f=checkstyle -reporter=github-pr-review`

this command will always return success code. Even if errors was produced by linter and successfully reported to github.

It would be handy to have an optional way to return non-zero exit code if at least one issue reported to github

**Comment by ruudk** [comment]
It appears that Reviewdog doesn't care for the exit code of the checker at all. If a command fails Reviewdog doesn't complain. This is very annoying because I was not aware that one of my checkers was bogus, and not checking at all! This gives a false sense of security.

**Comment by niclas-ahden** [comment]
>It appears that Reviewdog doesn't care for the exit code of the checker at all. If a command fails Reviewdog doesn't complain. This is very annoying because I was not aware that one of my checkers was bogus, and not checking at all! This gives a false sense of security.

I was bit by this today. reviewdog claimed that all checks were green despite the linter bins not having been installed properly 🤷‍♂ 

I'm thinking that this is a high-severity issue as you'll get silent false positives if anything is off in your build pipeline.

That being said, I really appreciate reviewdog and the work you're putting into it. Thank you!

**Comment by kostyay** [comment]
Same here, checks were always succeeding, but then I realized I didn't have any tools installed after running with -tee

**Comment by DmitryLanda** [comment]
It is not exactly same as requested - but I have created PR to fix that issue https://github.com/reviewdog/reviewdog/pull/504

I just realized that bypassing original code is not a good idea - as reviewdog uses `git diff` to filter out errors from code tthat was not changed in PR.

If you realy need it - you may use `set -o pipefail` before running spellchecker and reviedog
Example
```bash
set -o pipefail
php $HOME/bin/phpcs.phar --extensions=php --report=checkstyle ${DIFF_FILES}  | reviewdog -f=checkstyle -reporter=github-pr-review
```

But if you want to return failure ONLY if any violation found in git diff - you may give a try to my PR by adding `-fail-on-error=true` as an option. It will return `1` as exit code if any errors found in diff
