### ISSUE TITLE
escape message for markdown

### ISSUE THREAD

**Issue by haya14busa** [reviewdog/reviewdog#46]

**Comment by haya14busa** [comment]
ref: https://github.com/haya14busa/reviewdog/pull/45#pullrequestreview-7892297

**Comment by haya14busa** [comment]
Escaping (GitHub Fravor) markdown is not simple and some users intentionally use markdown as a message.

I don't have plan to implement it in the near future.

**Comment by Mustafaaydin34** [comment]
🚀
