### ISSUE TITLE
[github-pr-check,github-check] Support sub-directory run

### ISSUE THREAD

**Issue by haya14busa** [reviewdog/reviewdog#461]

**Comment by haya14busa** [comment]
related: https://github.com/reviewdog/action-golangci-lint/pull/15 https://github.com/reviewdog/action-eslint/pull/19

**Comment by ChadTaljaardt** [comment]
The team i work on would greatly benefit from this implementation.

**Comment by hazcod** [comment]
Was this my bug @haya14busa ?

**Comment by haya14busa** [comment]
Yes. sorry for the late update.

We can update some actions as well, so I'll reopen to track it.

- [ ] reviewdog/action-golangci-lint#15
- [ ] reviewdog/action-eslint#19

**Comment by haya14busa** [comment]
We need to release a new tag binary first #515.

**Comment by haya14busa** [comment]
Fixed!
