### ISSUE TITLE
New Linter: Ktlint

### ISSUE THREAD

**Issue by renatoabreu11** [reviewdog/reviewdog#464]
Hey!

I've created a new linter that uses ktlint and reviewdog. 
Repo: https://github.com/ScaCap/action-ktlint
Marketplace: https://github.com/marketplace/actions/run-ktlint-with-reviewdog

**Comment by haya14busa** [comment]
Awesome! :+1: Thank you for your work!

- I invited you to reviewdog org as action maintainers. Move the repository under the organization if you want. I actually either is fine.
- Can you create a PR to add the action to README?
- Can you take a look at https://github.com/reviewdog/action-template and copy the workflow?
