### ISSUE TITLE
Integration with Spotbugs

### ISSUE THREAD

**Issue by thanarino** [reviewdog/reviewdog#492]
I am trying to integrate ReviewDog to our code review process in our GitLab projects, but it does not report issues. I have the following configuration:

`cat ./build/reports/spotbugs/main.text | reviewdog -efm="%*\\w %\\w%\\ %*\\w: %m  At %f:[line %l]" -diff="git diff branch" -reporter="gitlab-mr-discussion" -name="spotbugs" -tee`

The above command only outputs the result of the Spotbugs scan, which is of the following format:

`X Y Z: message message message  At file.java:[line 22]`

The result only indicates the filename and type of the affected file, does reviewdog need the full path of the file in order to report to GitLab?

**Comment by haya14busa** [comment]
reviewdog needs full path or relative path to the project root repository.
