### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by OrangeSniper** [reviewdog/reviewdog#512]
I use this line in cmd: `curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
`
It gives this error
`'sh' is not recognized as an internal or external command,
operable program or batch file.`
I don't understand what or if I did anything wrong.

**Comment by haya14busa** [comment]
Are you using windows's cmd? I guess it's just 'sh' is not installed.
