### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by ruudk** [reviewdog/reviewdog#515]
Would it be possible to tag a new release? 🙏🏻

**Comment by nightah** [comment]
Would also love a release so we can utilise the `fail-on-error` option.
cc @haya14busa 🙏🏻

**Comment by haya14busa** [comment]
Sorry for the late response. I'll work on it in a few days.

Potentially, I'd like to set up (semi-)automated release process so that other contributors with write access can push the new binary.

**Comment by mgrachev** [comment]
It would be great.

**Comment by mgrachev** [comment]
> Potentially, I'd like to set up (semi-)automated release process so that other contributors with write access can push the new binary.
It would be great.

**Comment by nightah** [comment]
> Potentially, I'd like to set up (semi-)automated release process so that other contributors with write access can push the new binary.

I can help with this if you like.

Happy to open discussions around what you want and submit a PR, be it Travis, Buildkite or otherwise.

**Comment by ChadTaljaardt** [comment]
We really need to be able to run eslint in a subdirectory, is there a rough ETA on this release?

**Comment by haya14busa** [comment]
Released! https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md#v0100---2020-05-07
