### ISSUE TITLE
REVIEWDOG_GITHUB_API_TOKEN didn't work in PRs on travisCI

### ISSUE THREAD

**Issue by panjf2000** [reviewdog/reviewdog#521]
Hi,
I've set up the REVIEWDOG_GITHUB_API_TOKEN env variable in my .travis.yml and tested it by opening a PR with my Github account, everything went well (see https://travis-ci.com/github/panjf2000/gnet/jobs/316683223#L182), but when it comes to those PRs from other Github users, travis kept printing "REVIEWDOG_GITHUB_API_TOKEN is not set" and the `github-pr-preview` didn't work, see https://travis-ci.com/github/panjf2000/gnet/jobs/323026725#L252.

This is my .travis.yml: https://github.com/panjf2000/gnet/blob/master/.travis.yml, is there any wrong with it?

**Comment by panjf2000** [comment]
Any update?

**Comment by haya14busa** [comment]
This is not reviwedog issue and this is expected.  You cannot use secret env var from forked repo in Travis.
Use GitHub actions or Circle CI insteaad.
