### ISSUE TITLE
feature request: Allow showing violations for only added or changed lines

### ISSUE THREAD

**Issue by tmc** [reviewdog/reviewdog#534]

**Comment by haya14busa** [comment]
Which reviewdog version do you use?
I'm guessing you're building the latest head ver, right?

**Comment by haya14busa** [comment]
and which reporter do you use? Can you write more information?

Originally, reviewdog actually showed violations for only added/changed lines, but it's changed by  #450.
You can use `-filter-mode=added` flag for the original behavior, but I'm currently considering to change the default value of `-filter-mode` to `added` as well before the new release. cc/  @Le6ow5k1

**Comment by haya14busa** [comment]
Implemented. https://github.com/reviewdog/reviewdog#filter-mode
