### ISSUE TITLE
Make use of predefined CI_API_V4_URL instead of GITLAB_API

### ISSUE THREAD

**Issue by roobre** [reviewdog/reviewdog#563]
Since Gitlab 11.7, a variable containing the URL to the gitlab API v4 is automatically set by gitlab: [`CI_API_V4_URL`](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference).

reviewdog could use this instead of `GITLAB_API`, perhaps as a fall-back mechanism (try `GITLAB_API` first, fall back to `CI_API_V4_URL` if the former is not set) to not break existing configurations.

I have not checked the code but the change seems pretty straightforward, so I could probably work on a PR for this if you are interested.

**Comment by haya14busa** [comment]
Sounds good! Can you work on it?

**Comment by roobre** [comment]
I'll give it a shot :)
