### ISSUE TITLE
Use github-pr-check report on github-pr-review

### ISSUE THREAD

**Issue by mihailpozarski** [reviewdog/reviewdog#567]
Recently I switched from `Hound` to `reviewdog` for PR reviews using [action-rubocop](https://github.com/reviewdog/action-rubocop) and have notice that after `reviewdog` finish processing my code it always return a success status when using reporter: `github-pr-review` (it's ok as `reviewdog` succeded commenting the code). 

When I used `Hound` it would comment the code as well, but if there was an offense in the code, it would report a failure status, this was useful for blocking the merge button if not all guidelines of the project where met.

I think it would be nice if `reviewdog` could be configured to have a similar behaivor by having a report similar to `github-pr-check report`.

expected_behaivor: The first check would pass telling that the code was successfully reviewed but the report would return a failure (as the code has offenses) but wouldn't leave annotations.

<img width="704" alt="Captura de Pantalla 2020-05-07 a la(s) 5 23 40 p  m" src="https://user-images.githubusercontent.com/46308442/81346218-eb3f4b80-9087-11ea-8689-580450549e93.png">

thanks for coding this awesome software!

PD: Sorry for my bad english 😅

**Comment by haya14busa** [comment]
Latest release supports `-fail-on-error=true` now! https://github.com/reviewdog/reviewdog#exit-codes

**Comment by haya14busa** [comment]
Looks like action-rubocop is not updated yet. Sent https://github.com/reviewdog/action-rubocop/pull/9 
cc/ @mgrachev

**Comment by mgrachev** [comment]
Thank you. Merged 🐶

**Comment by haya14busa** [comment]
Thank you for the quick response!

@mihailpozarski can you take a look?

**Comment by mihailpozarski** [comment]
@haya14busa @mgrachev 
It runs smoothly! 

thank you very much reviewdog team!
