### ISSUE TITLE
On Self hosted gitlab i can't see review .

### ISSUE THREAD

**Issue by arslbbt** [reviewdog/reviewdog#576]
# reviewdog.yml

runner:
  golint:
    cmd: /var/opt/gitlab/go/bin/golint $(go list ./... | grep -v /vendor/)
    format: golint
    level: warning
  # govet:
  #   cmd: go vet $(go list ./... | grep -v /vendor/)
  #   format: govet
  # errcheck:
  #   cmd: errcheck -asserts -ignoretests -blank $(go list ./... | grep -v /vendor/)
  #   errorformat:
  #     - "%f:%l:%c:%m"
  #   level: warning
  staticcheck:
    cmd: /var/opt/gitlab/go/bin/staticcheck $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  misspell:
    cmd: /var/opt/gitlab/go/bin/misspell $(git ls-files)
    errorformat:
      - "%f:%l:%c: %m"
  unparam:
    cmd: /var/opt/gitlab/go/bin/unparam $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  revive:
    cmd: /var/opt/gitlab/go/bin/revive -config=.revive.toml $(go list ./... | grep -v /vendor/)
    format: golint
    level: warning
  # golangci:
  #   cmd: /var/opt/gitlab/go/bin/golangci-lint run --out-format=line-number ./...
  #   errorformat:
  #     - '%E%f:%l:%c: %m'
  #     - '%E%f:%l: %m'
  #     - '%C%.%#'
  #   level: warning

**Comment by haya14busa** [comment]
Please reopen it more detail information. How do you run the reviewdog? Does it success? Error message?

**Comment by arslbbt** [comment]
issue here is its not adding any comment on gitlab
