### ISSUE TITLE
reviewdog: this is not PullRequest build.

### ISSUE THREAD

**Issue by Meemaw** [reviewdog/reviewdog#587]
Hi!

I'm trying to integrate reviewdog with checkstyle and Github actions. I keep getting the "reviewdog: this is not PullRequest build." from reviewdog, even though it is a PR and other reviewdog actions are working.

Link to PR: https://github.com/Meemaw/Insight/pull/75/files#diff-fbb14557164bb96f182ecff206e2a57cR8

Link to check: https://github.com/Meemaw/Insight/pull/75/checks?check_run_id=682434835#step:7:9

**Comment by SpootyMcSpoot** [comment]
What was the issue with this? I've started seeing this in my CI pipelines with no new changes to logic.
