### ISSUE TITLE
Send suggestions in github-pr-review

### ISSUE THREAD

**Issue by felipecassiors** [reviewdog/reviewdog#624]
GitHub review comments accept suggestions, that can be easily accepted. I wonder if there is how to integrate this into the `github-pr-review`. One example of these suggestions can be seen in the following screen shot:

> ![uUwilm8QdS](https://user-images.githubusercontent.com/29582865/84335708-dadd2d80-ab6b-11ea-99bd-48cb3789f064.png)
> From https://github.com/price-search/api/pull/45#discussion_r438487816

**Comment by haya14busa** [comment]
Thanks for the request! Yeah, I had an idea in my mind. I filed #678 to track the summary.
