### ISSUE TITLE
[github-check] Errors in unchanged files are filtered when upgrading from v0.9.17 to v0.10.0 

### ISSUE THREAD

**Issue by ruudk** [reviewdog/reviewdog#637]
When I upgraded [from v0.9.17 to v0.10.0](https://github.com/reviewdog/reviewdog/compare/v0.9.17...v0.10.0) I noticed that files that were not changed in a PR are now filtered and therefore don't fail anymore.

If I understand correctly, the goal of `github-check` was to also work for non-changed files.
```
It's basically same as -reporter=github-pr-check except it works not only for Pull Request but also for commit and it reports results outside Pull Request diff too.
```

Am I missing something?

**Comment by ruudk** [comment]
Nevermind, this was caused by https://github.com/reviewdog/reviewdog#filter-mode

**Comment by haya14busa** [comment]
Thanks for the report. I should have documented it.

Update the README and CHANGELOG. #649
