### ISSUE TITLE
Allow mergeable suggestions in GitHub review comments

### ISSUE THREAD

**Issue by patcon** [reviewdog/reviewdog#660]
Prior art: https://github.com/r7kamura/danger-suggester

Basically, this feature allows a command to be run that attempts to "fix" issues (e.g., `npx eslint --fix src/`), and it uses the resulting `git diff` to generate comments that have the special suggestion syntax:

    ```suggestion
    the new line of code to suggest
    ```

Theoretically, would it be easy to add something like this to reviewdog?

Thanks for considering!

**Comment by haya14busa** [comment]
Note that some linters like eslint support to output lint message along with suggestions, so ideally we should prefer to outputting lint error message as well.

Suggestions based on diff should be still very useful as it provides suggestions support in a general way :+1:
