### ISSUE TITLE
fail-on-error doesnt fail with golang-ci-lint

### ISSUE THREAD

**Issue by roopakv** [reviewdog/reviewdog#661]
SO I have been trying to get fail on error to help with my lint job on CI but it doesn't seem to work with golang ci lint.

![image](https://user-images.githubusercontent.com/678239/86193186-27c77a80-bb00-11ea-804f-00ec7c0ca498.png)

In this case notice that it exists with 0 even with fail-on-error

I have tried the following variations
- `-fail-on-error`
- `-fail-on-error=true`
- `-fail-on-error="true"`

And though golang ci fails with exit 1, review dog seems to exit 0.

**Comment by haya14busa** [comment]
I'm guessing the finding is not in diff. reviwedog will exit with 1 only when it finds at least 1 finding in diff (or which are not filtered).
You can control the behavior with `-filter-mode`.
https://github.com/reviewdog/reviewdog#filter-mode

**Comment by roopakv** [comment]
@haya14busa so I did try the filter modes and ti didn't exit 1. But once i switched branches and came back it now seems to be fine. I am not sure anymore how I got to that state. I am going to close this out and re-open if i find a repro. 

thank you for the quick response
