### ISSUE TITLE
gerrit support

### ISSUE THREAD

**Issue by haya14busa** [reviewdog/reviewdog#69]

**Comment by haya14busa** [comment]
- List Revision Comments: https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-comments

**Comment by haya14busa** [comment]
We can use https://godoc.org/golang.org/x/build/gerrit package

**Comment by staticmukesh** [comment]
Hey @haya14busa, I would like to add Gerrit support in Reviewdog. Any concern?
