### ISSUE TITLE
Determining if reviewdog is working in GitHub Actions or not is broken because of runner's regression

### ISSUE THREAD

**Issue by polamjag** [reviewdog/reviewdog#708]
reviewdog checks for `GITHUB_ACTION` context variable in order to determine it's running in GitHub Actions or not. 

https://github.com/reviewdog/reviewdog/blob/31a1260dd0b95c3adb4629d8ef32e3207081d914/cienv/github_actions.go#L99-L103

However `GITHUB_ACTION` context variable has become empty in recent updates, so currently this check always fails.

ref. https://github.com/actions/runner/issues/635

As a result, running reviewdog in GitHub Actions always fails with this error: `reviewdog: cannot get repo owner from environment variable. Set CI_REPO_OWNER?`.

https://github.com/reviewdog/reviewdog/blob/c9d205fb4143e6c35c77f8885a27e71d666f90fb/cienv/cienv.go#L53-L55

I think this is a regression of GitHub Actions' runner, but I also think it's reasonable to mitigate this problem by checking another context variables such as `GITHUB_ACTIONS` like codecov/codecov-bash does:

https://github.com/codecov/codecov-bash/pull/341

**Comment by haya14busa** [comment]
For the record: [GITHUB_ACTION environment variable missing - breaking issue - GitHub Actions - GitHub Support Community](https://github.community/t/github-action-environment-variable-missing-breaking-issue/125913)
