### ISSUE TITLE
feat: add commitlint

### ISSUE THREAD

**Issue by timomayer** [reviewdog/reviewdog#730]
i want to see a commitlint action running and reporting to reviewdog so commit lint errors can also be reported
https://github.com/conventional-changelog/commitlint

**Comment by rickstaa** [comment]
@timomayer Feel free to create a pull-request. Let me know if you run into problems creating such an action.

**Comment by rickstaa** [comment]
@timomayer Closed due to inactivity. Feel free to respond to this issue if you still want to take on the project.
