### ISSUE TITLE
Thoughts on generalized action

### ISSUE THREAD

**Issue by xendk** [reviewdog/reviewdog#830]
A lot of linters (at least in our neck of the woods) are meant to be installed into the project rather than globally. For one thing, it ensures that CI and the local dev environment are using the same versions.

So a general reviewdog action would be handy, and one wouldn't have to create a new action for each new linter.

So I'm attempting to create a generalized action that can take the output of any command and pass it to reviewdog: https://github.com/reload/action-reviewdog (still much a work in progress).

I had to use a composite action in order to be able to run whatever command was configured (in most interpreted languages the linters also require the interpreter). But that messes with the nice depup action unfortunately.

What's your thought about this?

**Comment by rickstaa** [comment]
@xendk Perfect idea this will save us a lot of development hours! I started having this idea myself two days ago when I am developing the new [action-flake8](https://github.com/reviewdog/action-flake8). As it is writen in javascript it is extremely easy to translate it to a generalized action. I however was not aware of the [new composite actions](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action) very usefull! I think with that you can make a cleaner (multi-os supported) generalized action. If that doesn't work out we can use the [action-flake8](https://github.com/reviewdog/action-flake8) as a skeleton.

I just created a pull request for the depup action your experiencing [action-depup/21](https://github.com/haya14busa/action-depup/pull/21). Untill @haya14busa merged it into the master branch; you can use my branch [rickstaa/action-depup](https://github.com/haya14busa/action-depup). 

Keep me posted and feel to include me in issues might you need any help developing the action.

**Comment by xendk** [comment]
@rickstaa Excellent, your PR should take care of the problem of keeping reviewdog up to date.

I wasn't aware of composite actions either, until I realized that a docker based action wouldn't be able to access the right tools.

I've tested it with a PHP project, and it works great. Just needs a little cleanup and fixing the example screenshots.

One thing I was thinking: Not supplying a command should just run reviewdog, which will then look for a configuration file (it already does, if you leave out some arguments. Then one can configure all the linters in `.reviewdog.yml` and have one Github action run them all, which also works locally. Sadly we can't use it ourselves as we're running things in containers locally, which isn't needed in actions.

**Comment by rickstaa** [comment]
@xendkGreat! :rocket: I will test it out when I need to add a reviewdog option to a new repository.

I agree. Running it without arguments while supplying a `.reviewdog.yml` file provides a very clean way to use the generalized action. I think this should already work based on the action you created. I will also test this out when I find the time.

**Comment by haya14busa** [comment]
Hmm... that's an interesting idea but what do you think about the difference from https://github.com/reviewdog/action-setup?
action-setup can install reviewdog with the composite run and users can run whatever tools they want with reviewdog.

**Comment by rickstaa** [comment]
@haya14busa I think your right. As long as the next composite step correctly handles piping or the conig file is used the https://github.com/reviewdog/action-setup can be used to achieve the same result. In that case we only need to update the readme.md to give an example of such a combined use case. @xendk what do you think?

**Comment by xendk** [comment]
@hay

**Comment by xendk** [comment]
@haya14busa Well, technically there's not much difference, one can accomplish the same end goal using action-setup. It could be promoted a bit more, and perhaps being renamed to `setup-reviewdog` (that seems to be the common naming pattern).

But I'm thinking about workflow file readability, there's already enough noise in the setup actions one need for the language at hand, having another one and having to remeber the reviewdog command line switches seems suboptimal to me. I like the idea of having a single action to invoke a tool together with reviewdog, and not having to think about installing it.

**Comment by rickstaa** [comment]
@xendk I think I have to agree with @haya14busa that for my use cases the `action-setup` already achieves everything I need. I however agree with you on the fact that the current name `action-setup` is a bit confusing. I think renaming the action to `setup-reviewdog` or `action-setup-reviewdog` would make it for people to find it.

**Comment by xendk** [comment]
@rickstaa Well, I won't claim my suggestion would accomplish anything that cannot be done with action-setup, or curling the binary. I just think that the shorter one can make ones actions, the better. It makes the linter being run more prominent. Isn't that also the reason for all the `action-*` linters in the reviewdog org? Each of those could be replaced by action-setup too.

But the local winds seems to be blowing in the favour of problem matchers instead, so I'll probably not finish it anyway.

**Comment by rickstaa** [comment]
@xendk Good point. Everything in all the other `action-*` linters can indeed be achieved with the setup action or even a curl statement. I, therefore, think the discussion here is just a matter of personal preference. Nevertheless, I see no harm in adding your suggestion as it is a logical intermediate step between specific linter actions and the setup action. This way, people can choose which one they want to use. I also further thought about it. There are enough use-cases where your general composite action would be preferred over combining the setup-action with linting run commands or combining multiple `action-*` linter actions.

For example, if people want to use Reviewdog with a linter that has a specific action, they could use your suggestion without creating such action themselves or using a bunch of run commands.

Maybe let's see what @haya14busa and the rest of the @reviewdog/reviewdog community think about it.

**Comment by limakzi** [comment]
@rickstaa Why cant they doing so right now? It is a matter of minutes.

**Comment by rickstaa** [comment]
@limakzi Your right creating a specific action or use run commands shouldn't take long. I was just checking how the rest of the community felt about creating a generalized action. @xendk Feel free to close the issue whenever you think people have had enough time to comment on the surgesttion.
