### ISSUE TITLE
Transfer action-remark-lint to the organization

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/reviewdog#836]
@prologic, @asbjornu and me created a [GitHub action that lints markdown code](https://github.com/prologic/action-remark-lint/) and annotates them using reviewdog. I think it would make sense to transfer this action to the organization. Maybe somebody with admin rights can add @prologic to the organization so that we can go ahead and transfer the ownership.

**Comment by haya14busa** [comment]
Thank you for your work!
I invited @prologic and @asbjornu to the reviewdog org.

Please feel free to move the repo under the reviewdog org.
