### ISSUE TITLE
Reviewdog throws 'input data has violations' when the `fail-on-error` flag is used

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/reviewdog#848]
Whenever I add the `-fail-on-error` flag combined with the `-filter-mode` flag, I receive the `reviewdog: input data has violations` warning. 

## When does this happen
This happens only when warnings or errors are present. In this case, it also throws an exit `1` exit code (see test reports below). This is fine given [the documentation](https://github.com/reviewdog/reviewdog). The problem is that the exit code, however, also is thrown when only warnings are present. I, therefore, suspect something else is going wrong. Interestingly, this error only occurs for the `local` and `github-pr-review` reporters and not for the `github-check` reporter (I did not check the other reporters). Maybe this bug has to do with the fact that this combination is not yet supported([see the documentation](https://github.com/reviewdog/reviewdog#filter-mode-support-table))?

## What I already tried

- I tried using a different linter/formatter (black) for example but the issue also occurs.
- I tried changing adding double quotes to my reviewdog input arguments.
- I tried different `-fail-on-error` flag syntaxes (`-fail-on-error="true"` and `-fail_on_error=true`).
- I tried different report levels (`info`, `warning` and `error`). 

## How to reproduce

1. Clone [the example repository](https://github.com/rickstaa/reviewdog_fail_on_error_bug) I created for this bug.
2. Follow the steps in the readme.
3. See the problems appear.

## flake8 lint warnings test report

Let's test what happens when we enable `-fail-on-error` while the code vase contains linter warnings.

🧪 thttps://github.com/rickstaa/action-test-repo/pull/54

## Flake8 lint warning+errors test report

Let's test what happens when we enable `-fail-on-error` while the code vase contains linter warnings and errors.

🧪 https://github.com/rickstaa/action-test-repo/pull/55

**Comment by haya14busa** [comment]
It's actually working as intended. With `-fail-on-error`, it fails when reviewdog finds any results from linters regardless of the diagnostic level (error/warning/info).

Though I agree that it's confusing and `-fail-on-error` is not well-designed.

**Comment by rickstaa** [comment]
@haya14busa Okay that is good to know. In that case we might need to change the documentation a bit from:

``diff
-  If `-fail-on-error` flag is passed, reviewdog exits with `1` when at least one error/warning was found/reported.
+ If `-fail-on-error` flag is passed, reviewdog exits with `1` when at least one error/warning was found/reported.
```

Or we need to redesign the behavoir of the flag:

1. Let it only fail on errors (Bad for back-compatibility).
2. Let people define on which reviewdog should fail `-fail-level="warning"`. Keep the default on both warnings and errors.
3. Add a -fail-on-warning flag and let the -fail-on-error flag only fail on errors (Bad for back-compatibility).

**Comment by haya14busa** [comment]
As for the document, reviewdog still fails with info or diagnostics without any level, so it's still incorrect.

Option 2 looks good and similar to what I imagined, but the detailed design should be discussed more including exit-code handling in general.

**Comment by rickstaa** [comment]
@haya14busa Ah I see I didn't use it with linters that encountered the info or diagnostics tag. Let's go for option 2 then. I will draft a design note, containing the exit-code handling, for you to review when I find time to work on the feature.

**Comment by rickstaa** [comment]
@haya14busa I quickly went through the codebase and I currently do not have the resources to work on this myself. I created a seperate feature request on 856 might other people want to implement the feature.
