### ISSUE TITLE
reviewdog: this is not PullRequest build.

### ISSUE THREAD

**Issue by SpootyMcSpoot** [reviewdog/reviewdog#872]
I have just started seeing this error in my CircleCI pipeline (starting 2/4/21): `this is not PullRequest build` 

It is running against a PR commit for review:

`./bin/reviewdog -f=rubocop -reporter=github-pr-review`

Nothing has changed in our CI that would have caused this.

**Comment by haya14busa** [comment]
Please check p-r related env variables. https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
