### ISSUE TITLE
github-check reporter not working on workflow_dispatch event

### ISSUE THREAD

**Issue by skarzi** [reviewdog/reviewdog#873]
Hi :wave: 

first of all thanks for developing this great tool!

Recently I had experienced an issue related to `reviewdog` `github-check` reporter and GitHub Actions [`workflow_dispatch`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) event.

Here you can find some examples:
+ GitHub workflow's [job](https://github.com/skarzi/jenkins_configuration/blob/c062bf292f13f43abb26d4eb412f45639ddca69c/.github/workflows/lint.yml#L48) using [`action-markdownlint`](https://github.com/reviewdog/action-markdownlint)
+ successful [run](https://github.com/skarzi/jenkins_configuration/runs/1863704363?check_suite_focus=true) of this workflow on `push` event
+ failed [run](https://github.com/skarzi/jenkins_configuration/runs/1863710544?check_suite_focus=true) of this workflow on `workflow_dispatch` event

It seems like commit SHA is missed in `workflow_dispatch` event JSON, so `reviewdog` is ran with empty `BuildInfo.SHA` - [reference](https://github.com/reviewdog/reviewdog/blob/35294866e6beafab222b1e0ca2b728e19ad4dcdc/cienv/github_actions.go#L74).
Do you have any ideas for fix (like reading commit SHA from `GITHUB_SHA` env, etc.)?

**Comment by AlexTMjugador** [comment]
v0.14.2 includes a change that should fix this issue. If that's not the case, please feel free to let us know so we can reopen it.
