### ISSUE TITLE
Comment when file is generally modified/added/deleted

### ISSUE THREAD

**Issue by JensRantil** [reviewdog/reviewdog#92]
I have a use case where I'd like to make a comment to the reviewer as soon as an RPC data structure is modified. Essentially I want to ask if the deploy of the microservice is backwards compatible. In the best of worlds I'll implement an AST for Java parsing the source code and adding a warning by each field. That said, right now I'd happily just add a comment as soon as an RPC class file changes.

Question: In the readme all error formats contain a line. Is it possible to simply add a generic warning for a whole file (and warn if the file changes)? Any other approach? Is reviewdog the right tool for this?

**Comment by haya14busa** [comment]
>  Is it possible to simply add a generic warning for a whole file (and warn if the file changes)?

I have a plan to support it, but it's not possible right now.

It might be annoying to post false-positive file comments each time to PR which contains the file changed, so we need to consider when reviewdog should post file comments.

**Comment by JensRantil** [comment]
One idea is simply that line number 0, or negative line number, applies to the whole file. What do you think of that?

**Comment by JensRantil** [comment]
Please let me know if you'd be fine with the https://github.com/haya14busa/reviewdog/issues/92#issuecomment-299137785 approach mentioned above. I could consider submitting a pull request when I find the time if you'd be open to such a solution.

**Comment by JensRantil** [comment]
> It might be annoying to post false-positive file comments each time to PR which contains the file changed, so we need to consider when reviewdog should post file comments.

You have a point. I see this as two different things we need to address:

 1. Support for lint warning across ranges of lines, possibly also special identifier for "EOF" for generating a lint forwarning for last line in the file. A warning for the whole file could then be expressed as `1-EOF`.
 2. Defining if a warning should be generated for adding line, removing line, or both (that is modification).

Instead of filenumber <= 0 (as in #94), how about

 1. adding support for line ranges with `EOF` marker in `errorformat`? And
 2. introducing yet another [error format identifier](https://github.com/JensRantil/errorformat/blob/master/errorformat.go#L409), call it `%x`, which would be `a` for lines added, `r` for lines deleted and `ar` for lines modified? Obviously `%x` means that `errorformat` would diverge from vim's errorformat, but it might be worth it to support changes.

**Example:** Given an error format of `%f:%l:%x: %m` the linter line

    myfile.go:1-EOF:a: A line has been added.

would trigger a comment on the first added file anywhere in `myfile.go`. If multiple lines are added only a single (the first) line is commented on.

What do you think of this?

**Comment by haya14busa** [comment]
I'm so sorry for the late reply.

I don't think it's good idea to add new errorformat identifier.
If you wanna post a comment for whole file, just skipping line number is enough. `myfile.go: this file contains blah blah errors` for errorformat side.

And reviewdog can deal with it as line number == 0. No need to support negative line number.

it might be interesting to add range identifier to errorformat, but we don't need this feature to fix the issue.

As for the timing to post file comments, I have 2 option to consider.

1. Post file comments for every pull request containing file comment. If the comment is false positive, users can filter them by their own before passing lint result to reviewdog.
2. Post file comments only the file is added in the pull request. Unfortunately, it leads false negative.

I don't like both options, but I slightly prefer option 1.
What do you think?

**Comment by haya14busa** [comment]
Now you can use `-filter-mode=file`. https://github.com/reviewdog/reviewdog#filter-mode
