### ISSUE TITLE
Add explicit check annotation reporter

### ISSUE THREAD

**Issue by szechyjs** [reviewdog/reviewdog#943]
Currently the github actions check annotations are only used as a fallback. However, it would be nice to be able to explicitly use them. This would help consolidate the list of checks on a given PR. Currently each job gets added as a check, and then when using `gihtub-check` reporter it adds another check. When using the annotations it adds the report/annotations to the original job/check, thus preventing duplication.

**Comment by shogo82148** [comment]
https://github.com/reviewdog/reviewdog/pull/1623 will close this issue

**Comment by shogo82148** [comment]
closed by https://github.com/reviewdog/reviewdog/pull/1623
