### ISSUE TITLE
Reviewdog gets confused when proposing changes of code that include markdown

### ISSUE THREAD

**Issue by kellertuer** [reviewdog/reviewdog#999]
See here
https://github.com/JuliaManifolds/Manifolds.jl/pull/400#discussion_r672321087
where the code change included markdown, but since posted as a markdown comment, this got screwed up.

**Comment by shogo82148** [comment]
The document says it is needed to wrap them inside quadruple backticks.

https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

> To display triple backticks in a fenced code block, wrap them inside quadruple backticks.

<pre>
```` 
```
Look! You can see my backticks.
```
````
</pre>

```` 
```
Look! You can see my backticks.
```
````

**Comment by kellertuer** [comment]
Thanks, that could help.
But what if the code uses quadruple backticks? Then watchdog has to use quintruple ones?
